- name: Prepare a configuration directory for shelves frontend
  file:
    path: "{{ docker_config_dir }}/{{ service }}"
    state: directory
    mode: 0700

- name: Run shelves frontend service
  docker_container:
    name: "{{ service }}-frontend"
    image: marsik/shelves-frontend
    restart_policy: unless-stopped
  environment:
    API_SERVER: "https://{{ shelves_backend_hostname }}"
    API_BASE: ""
    API_NAMESPACE: "v1"
    VIRTUAL_HOST: "{{ shelves_frontend_hostname }}"
    VIRTUAL_PORT: 80
    LETSENCRYPT_HOST: "{{ shelves_frontend_hostname }}"
    LETSENCRYPT_EMAIL: "{{ shelves_frontend_email }}"

