- name: Prepare a configuration directory for shelves frontend
  file:
    path: "{{ docker.config_dir }}/{{ service }}"
    state: directory
    mode: 0700

- name: Copy over the docker compose configuration for shelves frontend
  template:
    src: docker-compose.yml
    dest: "{{ docker.config_dir }}/{{ service }}/docker-compose.yml"

- name: Run shelves frontend service using docker-compose
  command: docker-compose up -d
  args:
    chdir: "{{ docker.config_dir }}/{{ service }}"
  environment:
    API_VIRTUAL_HOST: "{{ shelves.backend.hostname }}"
    WEB_VIRTUAL_HOST: "{{ shelves.frontend.hostname }}"


