- name: Prepare a configuration directory for shelves frontend
  file:
    path: "{{ docker_config_dir }}/{{ service }}"
    state: directory
    mode: 0700

- name: Copy over the docker compose configuration for shelves frontend
  template:
    src: docker-compose.yml
    dest: "{{ docker_config_dir }}/{{ service }}/docker-compose.yml"

- name: Pull up-to-date images
  command: docker-compose pull --ignore-pull-failures
  args:
    chdir: "{{ docker_config_dir }}/{{ service }}"

- name: Run shelves frontend service using docker-compose
  command: docker-compose up -d
  args:
    chdir: "{{ docker_config_dir }}/{{ service }}"
  environment:
    API_VIRTUAL_HOST: "{{ shelves_backend_hostname }}"
    WEB_VIRTUAL_HOST: "{{ shelves_frontend_hostname }}"


