- name: Check validity of database root password
  fail: msg="The root password for the database has to be defined"
  when: owncloud_sec_db_root_password == ''

- name: Check validity of owncloud user password
  fail: msg="The user password for the database has to be defined"
  when: owncloud_sec_db_password == ''

- name: "Deploy owncloud service database"
  docker:
    image: mariadb:10.1
    name: "owncloud-database"
    env:
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: "{{ owncloud_sec_db_password }}"
      MYSQL_DATABASE: owncloud
      MYSQL_ROOT_PASSWORD: "{{ owncloud_sec_db_root_password }}"
    pull: always
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

- name: "Create owncloud volumes"
  command: "docker volume create --name={{ item }}"
  when: item and not item.startswith("/")
  with_items:
    - "{{ owncloud_vol_data }}"
    - "{{ owncloud_vol_apps }}"
    - "{{ owncloud_vol_config }}"

- name: "Deploy owncloud service"
  docker:
    image: owncloud
    name: "owncloud"
    links:
      - "owncloud-database"
    env:
      LETSENCRYPT_HOST: "{{ owncloud_hostname }}"
      LETSENCRYPT_EMAIL: "{{ owncloud_email }}"
      VIRTUAL_HOST: "{{ owncloud_hostname }}"
    volumes:
      - "{{ owncloud_vol_config }}:/var/www/html/config"
      - "{{ owncloud_vol_apps }}:/var/www/html/apps"
      - "{{ owncloud_vol_data }}:/var/www/html/data"
    pull: always
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

