- name: Check validity of database root password
  fail: msg="The root password for the database has to be defined"
  when: secret.owncloud.db_root_password == ''

- name: Check validity of owncloud user password
  fail: msg="The user password for the database has to be defined"
  when: secret.owncloud.db_password == ''

- name: "Deploy owncloud service database"
  docker:
    image: mariadb:10.1
    name: "owncloud-database"
    env:
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: "{{ secret.owncloud.db_password }}"
      MYSQL_DATABASE: owncloud
      MYSQL_ROOT_PASSWORD: "{{ secret.owncloud.db_root_password }}"
    pull: always
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

- name: "Deploy owncloud service"
  docker:
    image: owncloud
    name: "owncloud"
    links:
      - "owncloud-database"
    env:
      VIRTUAL_HOST: "{{ owncloud.hostname }}"
    volumes:
      - "{{ owncloud.data }}/config:/var/www/html/config"
      - "{{ owncloud.data }}/apps:/var/www/html/apps"
      - "{{ owncloud.data }}/data:/var/www/html/data"
    pull: always
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

