---
- name: Add Virt SIG CentOS repository
  copy:
    src: virt7-sig.repo
    dest: /etc/yum.repos.d/virt7-sig.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Docker packages
  yum:
    name: docker,docker-python
    state: installed


- name: Make sure docker is running
  service:
    name: docker
    state: started
    enabled: yes


