# template the application.properties and docker-compose.yml to the dest host
- name: Prepare a configuration directory for shelves backend
  file:
    path: "{{ docker.config_dir }}/{{ service }}"
    state: directory
    mode: 0700

- name: Copy over the docker compose configuration for shelves backend
  template:
    src: docker-compose.yml
    dest: "{{ docker.config_dir }}/{{ service }}/docker-compose.yml"

- name: Copy over the backend configuration
  template:
    src: application.properties
    dest: "{{ docker.config_dir }}/{{ service }}/application.properties"

- name: Create database volume
  command: docker volume create --name=shelves-database

- name: Create data volume
  command: docker volume create --name=shelves-data

- name: Run shelves backend service using docker-compose
  command: docker-compose up -d
  args:
    chdir: "{{ docker.config_dir }}/{{ service }}"
  environment:
    MYSQL_DATABASE: "{{ service }}"
    SHELVES_DATABASE: "{{ service }}-database"
    SHELVES_DATA: "{{ service }}-data"
    SHELVES_CONFIG: "{{ docker.config_dir }}/{{ service }}"
    API_VIRTUAL_HOST: "{{ shelves.backend.hostname }}"
    WEB_VIRTUAL_HOST: "{{ shelves.frontend.hostname }}"

