- name: Check validity of database root password
  fail: msg="The root password for the database has to be defined"
  when: shelves_sec_database_root_password == ''

- name: Check validity of database user password
  fail: msg="The user password for the database has to be defined"
  when: shelves_sec_database_password == ''

# template the application.properties and docker-compose.yml to the dest host
- name: Prepare a configuration directory for shelves backend
  file:
    path: "{{ docker_config_dir }}/{{ service }}"
    state: directory
    mode: 0700

- name: Copy over the docker compose configuration for shelves backend
  template:
    src: docker-compose.yml
    dest: "{{ docker_config_dir }}/{{ service }}/docker-compose.yml"

- name: Copy over the backend configuration
  template:
    src: application.properties
    dest: "{{ docker_config_dir }}/{{ service }}/application.properties"
  register: backconfig

- name: Copy over the backend proxy configuration
  template:
    src: nginx.conf
    dest: "/etc/nginx/vhost.d/{{ shelves_backend_hostname }}"

- name: Create database volume
  command: docker volume create --name=shelves-database

- name: Create data volume
  command: docker volume create --name=shelves-data

- name: Pull up-to-date images
  command: docker-compose pull --ignore-pull-failures
  args:
    chdir: "{{ docker_config_dir }}/{{ service }}"

- name: Restart shelves backend to apply new configuration
  when: backconfig.changed
  command: "docker-compose restart backend -t {{ docker_timeout }}"
  args:
    chdir: "{{ docker_config_dir }}/{{ service }}"
  environment:
    MYSQL_DATABASE: "{{ service }}"
    SHELVES_DATABASE: "{{ service }}-database"
    SHELVES_DATA: "{{ service }}-data"
    SHELVES_CONFIG: "{{ docker_config_dir }}/{{ service }}"
    API_VIRTUAL_HOST: "{{ shelves_backend_hostname }}"
    WEB_VIRTUAL_HOST: "{{ shelves_frontend_hostname }}"

- name: Run shelves backend service using docker-compose
  command: "docker-compose up -d -t {{ docker_timeout }}"
  args:
    chdir: "{{ docker_config_dir }}/{{ service }}"
  environment:
    MYSQL_DATABASE: "{{ service }}"
    SHELVES_DATABASE: "{{ service }}-database"
    SHELVES_DATA: "{{ service }}-data"
    SHELVES_CONFIG: "{{ docker_config_dir }}/{{ service }}"
    API_VIRTUAL_HOST: "{{ shelves_backend_hostname }}"
    WEB_VIRTUAL_HOST: "{{ shelves_frontend_hostname }}"
    COMPOSE_HTTP_TIMEOUT: "{{ docker_timeout }}"

- name: Configure local Prometheus to scrape the metrics
  template:
    src: prometheus.json
    dest: "{{ docker_config_dir }}/{{ prometheus_service }}/dyn_{{ service }}.json"
  when: prometheus_service

