scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'push'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-push:9091']

  - job_name: 'dynamic'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - "/etc/prometheus/dyn_*.json"

