- name: Install Fail2ban
  yum:
    name: fail2ban-systemd,fail2ban-server
    state: latest

- name: Remove Fail2ban firewalld integration
  yum:
    name: fail2ban-firewalld
    state: absent

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no


