- name: OS specific fail2ban and firewall tasks
  include_tasks: "deploy-{{ansible_os_family}}.yml"

- name: Configure Fail2ban logging
  copy:
    dest: /etc/fail2ban/fail2ban.local
    content: |
      [Definition]
      logtarget = SYSLOG

- name: Enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Enable ICMP
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Enable all connections from lo
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Enable all connections from docker
  iptables:
    chain: INPUT
    in_interface: docker+
    jump: ACCEPT
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Enable established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Enable SSH ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: ssh
    jump: ACCEPT
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Enable HTTP ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: http
    jump: ACCEPT
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Enable HTTPS ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: https
    jump: ACCEPT
    state: present
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6

- name: Reject all other traffic
  command: iptables -P INPUT DROP

