- name: Install Fail2ban
  yum:
    name: fail2ban-systemd,fail2ban-server
    state: latest

- name: Configure Fail2ban logging
  copy:
    dest: /etc/fail2ban/fail2ban.local
    content: |
      [Definition]
      logtarget = SYSLOG

- name: Remove Fail2ban firewalld integration
  yum:
    name: fail2ban-firewalld
    state: absent

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Enable ICMP
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
    state: present

- name: Enable all connections from lo
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    state: present

- name: Enable all connections from docker
  iptables:
    chain: INPUT
    in_interface: docker+
    jump: ACCEPT
    state: present

- name: Enable established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present

- name: Enable SSH ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: ssh
    jump: ACCEPT
    state: present

- name: Enable HTTP ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: http
    jump: ACCEPT
    state: present

- name: Enable HTTPS ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: https
    jump: ACCEPT
    state: present

- name: Reject all other traffic
  command: iptables -P INPUT DROP

