- name: "Update systemd to mount proper cgroups for Docker support"
  replace: >
    dest=/etc/systemd/system.conf
    regexp='^#JoinControllers=.*$'
    replace='JoinControllers=cpu,cpuacct,cpuset freezer,devices'
    backup=yes
  register: config

- name: Restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: config.changed

- name: Waiting for server to come back
  connection: local
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 1
    timeout: 300
    state: started
  become: false
  when: config.changed

- name: Install yum versionlock
  yum:
    name: yum-plugin-versionlock
    state: installed

- name: Lock Docker to 1.10
  command: yum versionlock docker-1.10.3-46.el7.14

# JoinControllers=cpu,cpuacct,cpuset freezer,devices
- name: Prepare docker systemd override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Make sure mount propagation is set correctly
  copy:
    src: clear_mount_flags.conf
    dest: /etc/systemd/system/docker.service.d/
  register: docker_service_updated

- name: Reload docker
  systemd:
    enabled: yes
    daemon_reload: yes
    name: docker
    state: restarted
  when: docker_service_updated.changed
