- name: Nginx reverse proxy
  docker:
    name: nginx-reverse-proxy
    image: eforce21/letsencrypt-nginx-proxy:1.0.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    env:
      LETSENCRYPT_EMAIL: "info@marsik.org"
    pull: always
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

