- name: Create the Lets encrypt certificate directory
  file:
    path: /etc/ssl/certs/letsencrypt
    mode: 0700
    state: directory

- name: Create vhost customization directory
  file:
    path: /etc/nginx/vhost.d
    mode: 0755
    state: directory

- name: Nginx reverse proxy
  docker:
    name: nginx-reverse-proxy
    image: jwilder/nginx-proxy
    net: bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/letsencrypt:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    pull: always
    timeout: "{{ docker_timeout }}"
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

- name: Lets encrypt certificate service
  docker:
    name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    net: bridge
    volumes:
      - /etc/ssl/certs/letsencrypt:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-reverse-proxy
    pull: always
    timeout: "{{ docker_timeout }}"
    restart_policy: always
    restart_policy_retry: 20
    state: reloaded

