# This playbook prepares and installs the Prometheus time series
# database and the push endpoint.

---
- name: Check validity of grafana admin password
  fail: msg="The grafana admin password has to be defined"
  when: grafana_sec_password == ''

- name: Prometheus data volume
  command: "docker volume create --name={{ service }}-db-data"

# template the application.properties and docker-compose.yml to the dest host
- name: "Prepare a configuration directory for {{ service }}"
  file:
    path: "{{ docker_config_dir }}/{{ service }}"
    state: directory
    mode: 0700

- name: Copy over the prometheus configuration
  copy:
    src: prometheus.yml
    dest: "{{ docker_config_dir }}/{{ service }}/prometheus.yml"
  register: promcfg

- name: Prometheus push gateway
  register: prompush
  docker_container:
    name: prometheus-push
    image: prom/pushgateway
    networks:
      - name: "{{ service }}_net"
      - name: bridge
    expose: 9091
    pull: True
    restart_policy: unless-stopped
    restart_retries: 10
    state: started
    timeout: "{{ docker_timeout }}"
    env:
      VIRTUAL_HOST: "push.{{ prometheus_hostname }}"
      LETSENCRYPT_HOST: "push.{{ prometheus_hostname }}"
      LETSENCRYPT_EMAIL: "{{ prometheus_email }}"

- name: Prometheus time series db
  register: prometheus
  docker_container:
    name: "{{ service }}-db"
    image: prom/prometheus
    networks:
      - name: "{{ service }}_net"
      - name: bridge
    expose: 9090
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - "{{ service }}-db-data:/prometheus"
      - "{{ docker_config_dir }}/{{ service }}:/etc/prometheus"
    pull: True
    restart_policy: unless-stopped
    restart_retries: 10
    state: started
    restart: "{{ promcfg |changed }}"
    timeout: "{{ docker_timeout }}"
    env:
      PUSH_GW: 9091
      VIRTUAL_HOST: "{{ prometheus_hostname }}"
      LETSENCRYPT_HOST: "{{ prometheus_hostname }}"
      LETSENCRYPT_EMAIL: "{{ prometheus_email }}"

- name: Grafana dabase volume
  command: docker volume create --name=grafana-db

- name: Grafana config volume
  command: docker volume create --name=grafana-etc

- name: Graphing service
  register: grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    networks:
      - name: "{{ service }}_net"
      - name: bridge
    expose: 3000
    volumes:
      - grafana-db:/var/lib/grafana
      - /etc/grafana
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_sec_password }}"
      VIRTUAL_HOST: "{{ grafana_hostname }}"
      LETSENCRYPT_HOST: "{{ grafana_hostname }}"
      LETSENCRYPT_EMAIL: "{{ grafana_email }}"
    pull: True
    restart_policy: unless-stopped
    restart_retries: 10
    state: started
    timeout: "{{ docker_timeout }}"

...

